services:
  gym-adminDB:
    container_name: gym-adminDB
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gymAdminDB
    volumes:
      - ./postgres:/var/lib/postgresql/data